#!/bin/bash
set -xe

VER=2.16.0

if [ "$1" == "clean" ]; then
  rm -rf hypre lib obj include *.tar.gz *.o 2>/dev/null
  exit 0
fi

if [ ! -f ./lib/libHYPRE.a ]; then
  rm -rf hypre 2>/dev/null

  HYPRE_TAR=${NEKRS_SRC_THIRD_PARTY_DIR}/hypre.tgz
  if [ -f ${HYPRE_TAR} ]; then
    tar -xvf ${HYPRE_TAR}
  else
    git clone --depth 1 https://github.com/hypre-space/hypre.git
  fi

  cd hypre
  mkdir -p build
  cd build

  set -x
  cmake \
  -DHYPRE_MIXEDINT=ON \
  -DHYPRE_SINGLE=OFF \
  -DHYPRE_INSTALL_PREFIX=`pwd`/../.. \
  -DBUILD_SHARED_LIBS=ON \
  -DHYPRE_USING_HYPRE_BLAS=OFF \
  -DHYPRE_USING_HYPRE_LAPACK=OFF \
  -DHYPRE_USING_OPENMP=OFF \
  -DMPI_C_COMPILER=`which $CC` \
  -DHYPRE_USING_FEI=OFF \
  ../src
  set +x
  cd ../..

fi

cd hypre/build
make -j4 install
